(function(U){
  U.update=function(dt){const p=U.player,k=U.input.keys;let dx=(k.d||k.arrowright?1:0)-(k.a||k.arrowleft?1:0)+U.input.jx,dy=(k.s||k.arrowdown?1:0)-(k.w||k.arrowup?1:0)+U.input.jy,m=Math.hypot(dx,dy);if(m>1){dx/=m;dy/=m}p.vx=dx*p.speed;p.vy=dy*p.speed;if(Math.abs(dx)>Math.abs(dy)&&Math.abs(dx)>.1)p.facing=dx>0?'right':'left';else if(Math.abs(dy)>.1)p.facing=dy>0?'down':'up';p.x+=p.vx*dt;p.y+=p.vy*dt;p.anim+=dt*(m>.05?1:0);p.playTime+=dt;p.attackCd=Math.max(0,p.attackCd-dt);p.spellCd=Math.max(0,p.spellCd-dt);p.healCd=Math.max(0,p.healCd-dt);p.attackAnim=Math.max(0,p.attackAnim-dt);p.hitAnim=Math.max(0,(p.hitAnim||0)-dt);p.deathAnim=Math.max(0,(p.deathAnim||0)-dt);p.mana=Math.min(p.maxMana,p.mana+dt*(1.5+p.skills.Concentración*.015));p.stam=Math.min(p.maxStam,p.stam+dt*8);
    if(p.bandaging){p.bandaging.t-=dt;if(p.bandaging.t<=0){if(p.bandaging.gather==='mine'){U.addItem(Math.random()<.28?'copperOre':'ironOre',Math.round(U.rnd(4,8)));U.raiseSkill('Minería',.25)}else if(p.bandaging.gather==='wood'){U.addItem('wood',Math.round(U.rnd(4,8)));U.raiseSkill('Tala',.25)}else if(p.bandaging.gather==='fish'){U.addItem('fish',1);U.raiseSkill('Pesca',.25)}else{p.hp=Math.min(p.maxHp,p.hp+28+p.skills.Curar*.12);p.healCd=2.5;U.toast('Terminas de vendarte.')}p.bandaging=null;U.ui.refreshAll()}}
    if(U.state.autoAttack&&U.state.battle&&p.target&&!p.target.dead)U.attack();
    U.state.safeZone=U.cities.some(c=>Math.hypot(p.x-c.x,p.y-c.y)<c.safe);for(const e of U.enemies){if(e.dead)continue;e.hitAnim=Math.max(0,(e.hitAnim||0)-dt);e.attackCd=Math.max(0,e.attackCd-dt);e.moving=false;const d=U.dist(e,p);if(!U.state.safeZone&&d<8&&d>1.1){const q=e.speed*dt;e.x+=(p.x-e.x)/d*q;e.y+=(p.y-e.y)/d*q;e.moving=true;e.facing=Math.abs(p.x-e.x)>Math.abs(p.y-e.y)?(p.x>e.x?'right':'left'):(p.y>e.y?'down':'up')}if(e.moving)e.anim=(e.anim||0)+dt;if(!U.state.safeZone&&d<1.3&&e.attackCd<=0){e.attackCd=1.2;p.hp-=e.dmg;U.state.effects.push({type:'float',x:p.x,y:p.y,text:'-'+e.dmg,color:'#ff9a91',life:1});if(p.hp<=0)U.die()}}
    for(let i=U.state.projectiles.length-1;i>=0;i--){const pr=U.state.projectiles[i],t=pr.target;if(!t||t.dead){U.state.projectiles.splice(i,1);continue}const d=U.dist(pr,t),q=pr.speed*dt;if(d<q+.25){let dmg=pr.damage;if(pr.spell)dmg=18+U.player.skills.Magia*.11+(pr.spell.id==='lightning'?9:0);U.hitEnemy(t,dmg);U.state.projectiles.splice(i,1)}else{pr.x+=(t.x-pr.x)/d*q;pr.y+=(t.y-pr.y)/d*q}}
    for(let i=U.state.effects.length-1;i>=0;i--){const ef=U.state.effects[i];ef.life-=dt;if(ef.life<=0)U.state.effects.splice(i,1)}for(let i=U.state.corpses.length-1;i>=0;i--){U.state.corpses[i].life-=dt;if(U.state.corpses[i].life<=0)U.state.corpses.splice(i,1)}
    const sp=U.worldToScreen(p.x,p.y);U.camera.x+=(sp.x-U.W/2)*.12;U.camera.y+=(sp.y-U.H/2)*.12;U.ui.refreshHUD();U.ui.updateBattleUI();U.ui.updateContextAction()};
  U.die=function(){if(U.player.dead)return;U.player.dead=true;const dropped=[];for(let i=U.player.inventory.length-1;i>=0;i--)dropped.push(U.player.inventory.splice(i,1)[0]);for(const slot of Object.keys(U.player.equipment)){const it=U.player.equipment[slot];if(!it.insured){it.recoverySlot=slot;dropped.push(it);delete U.player.equipment[slot]}}U.state.corpses.push({name:'Tu cadáver',x:U.player.x,y:U.player.y,items:dropped,life:300,owner:'player',isPlayerCorpse:true});U.player.hp=U.player.maxHp;U.player.mana=U.player.maxMana;U.player.x=U.player.respawn.x;U.player.y=U.player.respawn.y;U.player.dead=false;U.player.target=null;U.state.autoAttack=false;U.toast('Has muerto y reapareces en '+U.player.respawn.name);U.ui.refreshAll()};
  U.save=function(){localStorage.setItem('ultra_v56',JSON.stringify({player:{...U.player,target:null,bandaging:null},state:{...U.state,projectiles:[],effects:[],currentCorpse:null,vendor:null},enemies:U.enemies}));U.toast('Partida guardada.')};
  U.load=function(){const raw=localStorage.getItem('ultra_v56')||localStorage.getItem('ultra_v55')||localStorage.getItem('ultra_v52')||localStorage.getItem('ultra_v51');if(!raw)return U.toast('No hay guardado.');const d=JSON.parse(raw);Object.assign(U.player,d.player);Object.assign(U.state,d.state);for(const cat in U.SKILLS)for(const sk of U.SKILLS[cat]){U.player.skills[sk]=Math.max(50,U.player.skills[sk]||50);U.player.skillLocks[sk]=U.player.skillLocks[sk]||'up'}U.enemies.splice(0,U.enemies.length,...(d.enemies||[]));U.normalizeInventory();U.ui.refreshAll();U.toast('Partida cargada y objetos apilados.')};
  U.reset=function(){localStorage.removeItem('ultra_v55');localStorage.removeItem('ultra_v52');localStorage.removeItem('ultra_v51');location.reload()};
  U.loop=function(now){const dt=Math.min(.033,(now-U.last)/1000);U.last=now;U.update(dt);U.draw();requestAnimationFrame(U.loop)};
})(window.Ultra=window.Ultra||{});
