import {WorldMap} from '../world/map.js';import {makeEnemies} from '../world/entities.js';import {Player} from '../character/player.js';import {Camera} from './camera.js';import {Input} from './input.js';import {CombatSystem} from '../systems/combat.js';import {HealingSystem} from '../systems/healing.js';import {GatheringSystem} from '../systems/gathering.js';import {CraftingSystem} from '../systems/crafting.js';import {UI} from '../ui/hud.js';import {ITEMS} from '../data/items.js';
export class Game{
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.world=new WorldMap();this.player=new Player();this.enemies=makeEnemies();this.corpses=[];this.projectiles=[];this.texts=[];this.input=new Input();this.camera=new Camera(canvas,this.world);this.combat=new CombatSystem(this);this.healing=new HealingSystem(this);this.gathering=new GatheringSystem(this);this.crafting=new CraftingSystem(this);this.ui=new UI(this);this.last=performance.now();this.resize();addEventListener('resize',()=>this.resize());this.ui.renderAll();requestAnimationFrame(t=>this.loop(t))}
  resize(){const dpr=Math.min(devicePixelRatio||1,2),r=this.canvas.getBoundingClientRect();this.canvas.width=Math.round(r.width*dpr);this.canvas.height=Math.round(r.height*dpr);this.ctx.setTransform(dpr,0,0,dpr,0,0);this.canvas.widthCss=r.width;this.canvas.heightCss=r.height;this.camera.canvas={width:r.width,height:r.height}}
  loop(now){const dt=Math.min(.033,(now-this.last)/1000);this.last=now;this.update(dt);this.draw();requestAnimationFrame(t=>this.loop(t))}
  update(dt){const p=this.player;if(p.dead){this.handleDeath()}else{p.update(dt,this.input.vector(),this.world);for(const e of this.enemies)e.update(dt,p,this.world)}this.camera.update(p);for(const pr of this.projectiles)pr.life-=dt;this.projectiles=this.projectiles.filter(p=>p.life>0);for(const t of this.texts)t.life-=dt;this.texts=this.texts.filter(t=>t.life>0);this.ui.renderHud()}
  handleDeath(){if(this.deathHandled)return;this.deathHandled=true;const dropped=[];for(const item of [...this.player.inventory.items]){const def=ITEMS[item.id];if((def.type==='weapon'||def.type==='armor')&&item.insured)continue;dropped.push({id:item.id,qty:item.qty});this.player.inventory.items=this.player.inventory.items.filter(i=>i.uid!==item.uid)}for(const[slot,item]of Object.entries(this.player.equipment.slots)){if(!item)continue;const def=ITEMS[item.id];if(!item.insured){dropped.push({id:item.id,qty:1});this.player.equipment.slots[slot]=null}}this.corpses.push({x:this.player.x,y:this.player.y,owner:'jugador',items:dropped,radius:17});this.toast('Has muerto. Tu equipo no asegurado quedó en el cuerpo.','bad');setTimeout(()=>{this.player.x=this.player.checkpoint.x;this.player.y=this.player.checkpoint.y;this.player.hp=this.player.maxHp;this.player.mana=this.player.maxMana;this.player.stamina=this.player.maxStamina;this.player.dead=false;this.deathHandled=false;this.ui.renderAll()},1400)}
  use(){const p=this.player;const corpse=this.corpses.find(c=>Math.hypot(c.x-p.x,c.y-p.y)<45&&c.items.length);if(corpse){for(const it of corpse.items)p.inventory.add(it.id,it.qty);corpse.items=[];this.toast('Cadáver saqueado','good');this.ui.renderAll();return}if(this.world.isCity(p.x,p.y)){p.checkpoint={x:p.x,y:p.y};this.toast('Punto de control guardado en la ciudad','good');return}this.toast('No hay nada que usar')}
  toast(text,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=text;document.getElementById('toast-stack').append(el);setTimeout(()=>el.remove(),2200)}
  floatText(x,y,text){this.texts.push({x,y,text,life:1})}
  draw(){const ctx=this.ctx,w=this.canvas.widthCss,h=this.canvas.heightCss;ctx.clearRect(0,0,w,h);this.world.draw(ctx,this.camera);ctx.save();ctx.translate(-this.camera.x,-this.camera.y);for(const c of this.corpses){ctx.fillStyle=c.items.length?'#3b201c':'#25211f';ctx.beginPath();ctx.ellipse(c.x,c.y,18,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d8c7a4';ctx.font='11px system-ui';ctx.fillText(c.items.length?'Cadáver':'Vacío',c.x-22,c.y-13)}for(const e of this.enemies){if(e.dead)continue;ctx.fillStyle=e.color;ctx.beginPath();ctx.arc(e.x,e.y,e.radius,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1b1210';ctx.fillRect(e.x-16,e.y-22,32,4);ctx.fillStyle='#b94239';ctx.fillRect(e.x-16,e.y-22,32*(e.hp/e.maxHp),4)}for(const pr of this.projectiles){const t=1-pr.life/.45;ctx.fillStyle='#ff8a35';ctx.beginPath();ctx.arc(pr.x+(pr.target.x-pr.x)*t,pr.y+(pr.target.y-pr.y)*t,7,0,Math.PI*2);ctx.fill()}const p=this.player;ctx.fillStyle=p.dead?'#6f6258':p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.radius,0,Math.PI*2);ctx.fill();ctx.strokeStyle=p.battle?'#c84d42':'#d8b56a';ctx.lineWidth=3;ctx.stroke();ctx.strokeStyle='#eee';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+p.facing.x*22,p.y+p.facing.y*22);ctx.stroke();for(const t of this.texts){ctx.globalAlpha=t.life;ctx.fillStyle='#ffe4a8';ctx.font='bold 14px system-ui';ctx.fillText(t.text,t.x,t.y-(1-t.life)*28);ctx.globalAlpha=1}ctx.restore()}
}
