(function(U){
  U.initCanvas=function(){U.canvas=U.$('#game');U.ctx=U.canvas.getContext('2d');U.resize=function(){U.DPR=Math.min(2,devicePixelRatio||1);U.W=innerWidth;U.H=innerHeight;U.canvas.width=U.W*U.DPR;U.canvas.height=U.H*U.DPR;U.ctx.setTransform(U.DPR,0,0,U.DPR,0,0)};addEventListener('resize',U.resize);U.resize();U.worldToScreen=(x,y,z=0)=>({x:(x-y)*32+U.W/2-U.camera.x,y:(x+y)*16+U.H/2-U.camera.y-z});U.screenToWorld=(sx,sy)=>{const X=(sx-U.W/2+U.camera.x)/32,Y=(sy-U.H/2+U.camera.y)/16;return{x:(X+Y)/2,y:(Y-X)/2}}};
  function diamond(x,y,fill,stroke='#29352a'){const p=U.worldToScreen(x,y);U.ctx.beginPath();U.ctx.moveTo(p.x,p.y-16);U.ctx.lineTo(p.x+32,p.y);U.ctx.lineTo(p.x,p.y+16);U.ctx.lineTo(p.x-32,p.y);U.ctx.closePath();U.ctx.fillStyle=fill;U.ctx.fill();U.ctx.strokeStyle=stroke;U.ctx.stroke()}
  function hpBar(o,p){const c=U.ctx,w=o.boss||o.variant==='renowned'?58:o.variant==='exalted'?46:38,h=5;c.fillStyle='#18110f';c.fillRect(p.x-w/2,p.y-64,w,h);c.fillStyle=o.hp/o.maxHp>.45?'#a8463f':'#d76a54';c.fillRect(p.x-w/2+1,p.y-63,(w-2)*Math.max(0,o.hp/o.maxHp),h-2);c.strokeStyle='#d8c7a1';c.strokeRect(p.x-w/2,p.y-64,w,h)}
  function label(o,p,isPlayer=false){const c=U.ctx,name=isPlayer?'Tú':o.name||'';c.font=`${o.variant||o.boss?'bold ':''}11px Arial`;c.textAlign='center';c.fillStyle=isPlayer?'#e9dfc8':(o.nameColor||'#ddd');c.strokeStyle='#000';c.lineWidth=3;c.strokeText(name,p.x,p.y-49);c.fillText(name,p.x,p.y-49);c.textAlign='start'}
  function drawFace(c,dir){c.fillStyle='#2a211b';if(dir==='up'){c.fillRect(-5,-35,10,4);return}if(dir==='left'){c.fillRect(-5,-32,2,2);c.beginPath();c.moveTo(-8,-29);c.lineTo(-12,-27);c.lineTo(-7,-26);c.fill();return}if(dir==='right'){c.fillRect(3,-32,2,2);c.beginPath();c.moveTo(8,-29);c.lineTo(12,-27);c.lineTo(7,-26);c.fill();return}c.fillRect(-4,-32,2,2);c.fillRect(3,-32,2,2);c.fillRect(-2,-27,4,1)}
  function weaponPose(skill,attack,dir){const t=attack?1:0;if(skill==='Arco')return{rot:t?-.15:-1.05,len:29,bow:true};if(skill==='Esgrima')return{rot:t?-.15:-.5,len:34,spear:true};if(skill==='Armas contundentes')return{rot:t?-1.8:-.55,len:25,heavy:true};if(skill==='Pelea')return{rot:t?-.1:-.5,len:12,fist:true};return{rot:t?-1.7:-.4,len:29,sword:true}}
  function humanoid(o,isPlayer=false){const c=U.ctx,p=U.worldToScreen(o.x,o.y,6),moving=isPlayer?Math.hypot(o.vx||0,o.vy||0)>.1:!!o.moving,phase=Math.sin((o.anim||0)*10),attack=(o.attackAnim||0)>0,dir=o.facing||'down';c.save();c.translate(p.x,p.y);if(U.CharacterRenderer&&U.CharacterAdapter){if(isPlayer){c.strokeStyle=U.state.battle?'#e26a61':'#c9ad70';c.lineWidth=2;c.beginPath();c.ellipse(0,8,16,7,0,0,Math.PI*2);c.stroke()}U.CharacterRenderer.draw(c,U.CharacterAdapter.getState(o));c.restore();label(o,p,isPlayer);if(!isPlayer&&o.hp!==undefined)hpBar(o,p);return}
    const side=dir==='left'?-1:dir==='right'?1:0,depth=dir==='up'?-1:1,leg=moving?phase*8:0;
    c.strokeStyle=o.color||'#886';c.lineWidth=8;c.lineCap='round';c.beginPath();c.moveTo(-4,9);c.lineTo(-7+leg*.45,37);c.moveTo(4,9);c.lineTo(7-leg*.45,37);c.stroke();
    c.fillStyle=o.hitAnim>0?'#c97d74':o.color||'#886';c.beginPath();c.ellipse(0,-3,dir==='left'||dir==='right'?11:14,25,0,0,Math.PI*2);c.fill();
    c.strokeStyle=o.color||'#886';c.lineWidth=7;c.beginPath();c.moveTo(-5,-17);c.lineTo(-15-leg*.25,7);c.moveTo(5,-17);c.lineTo(15+leg*.25,7);c.stroke();
    c.fillStyle='#a77f61';c.beginPath();c.arc(side*2,-31,8,0,Math.PI*2);c.fill();drawFace(c,dir);
    if(isPlayer&&U.player.equipment.shield){const sx=dir==='right'?-18:dir==='left'?18:-18,sy=dir==='up'?-7:-2;c.fillStyle='#6f7780';c.beginPath();c.ellipse(sx,sy,9,13,-.25,0,Math.PI*2);c.fill();c.strokeStyle='#bbc2c6';c.lineWidth=2;c.stroke()}
    if(isPlayer&&U.player.equipment.weapon){const d=U.itemDefs[U.player.equipment.weapon.id],pose=weaponPose(d.skill,attack,dir),handX=dir==='left'?-16:16;c.save();c.translate(handX,1);c.scale(dir==='left'?-1:1,1);c.rotate(pose.rot);if(pose.bow){c.strokeStyle='#9a6d38';c.lineWidth=3;c.beginPath();c.arc(11,0,15,-1.2,1.2);c.stroke();c.strokeStyle='#ddd';c.lineWidth=1;c.beginPath();c.moveTo(16,-14);c.lineTo(16,14);c.stroke()}else if(pose.fist){c.fillStyle='#8c6a50';c.beginPath();c.arc(11,0,7,0,Math.PI*2);c.fill()}else{c.strokeStyle=pose.heavy?'#aaa':'#dedede';c.lineWidth=pose.spear?3:pose.heavy?7:4;c.beginPath();c.moveTo(0,0);c.lineTo(pose.len,-4);c.stroke();if(pose.spear){c.fillStyle='#d8d8d8';c.beginPath();c.moveTo(pose.len,-4);c.lineTo(pose.len-8,-9);c.lineTo(pose.len-8,1);c.fill()}if(pose.heavy){c.strokeStyle='#7a4b2a';c.lineWidth=5;c.beginPath();c.moveTo(pose.len-5,-12);c.lineTo(pose.len-5,5);c.stroke()}}c.restore()}
    c.restore();label(o,p,isPlayer);if(!isPlayer)hpBar(o,p)}
  function wolf(o){const c=U.ctx,p=U.worldToScreen(o.x,o.y,2),q=o.moving?Math.sin((o.anim||0)*11)*3:0;c.save();c.translate(p.x,p.y);c.fillStyle=o.hitAnim>0?'#b9776d':o.color;c.beginPath();c.ellipse(0,-10,o.variant?23:20,o.variant?12:10,0,0,Math.PI*2);c.fill();c.beginPath();c.ellipse(18,-17,9,7,0,0,Math.PI*2);c.fill();c.beginPath();c.moveTo(15,-24);c.lineTo(18,-33);c.lineTo(22,-23);c.fill();c.strokeStyle=o.color;c.lineWidth=5;for(const x of [-12,-3,8,16]){c.beginPath();c.moveTo(x,-4);c.lineTo(x+q,10);c.stroke()}c.restore();label(o,p);hpBar(o,p)}
  function troll(o){const c=U.ctx,p=U.worldToScreen(o.x,o.y,4),q=o.moving?Math.sin((o.anim||0)*6)*5:0,sc=o.variant==='renowned'||o.boss?1.35:o.variant==='exalted'?1.15:1;c.save();c.translate(p.x,p.y);c.scale(sc,sc);c.fillStyle=o.hitAnim>0?'#9a7468':o.color;c.beginPath();c.ellipse(0,-10,23,31,0,0,Math.PI*2);c.fill();c.beginPath();c.arc(0,-43,14,0,Math.PI*2);c.fill();c.strokeStyle='#48613f';c.lineWidth=12;c.lineCap='round';c.beginPath();c.moveTo(-18,-20);c.lineTo(-30-q,10);c.moveTo(18,-20);c.lineTo(30+q,10);c.moveTo(-9,16);c.lineTo(-12+q,42);c.moveTo(9,16);c.lineTo(12-q,42);c.stroke();c.restore();label(o,p);hpBar(o,p)}
  U.draw=function(){const c=U.ctx;c.clearRect(0,0,U.W,U.H);const span=24;for(let y=Math.floor(U.player.y)-span;y<Math.floor(U.player.y)+span;y++)for(let x=Math.floor(U.player.x)-span;x<Math.floor(U.player.x)+span;x++){let fill='#203a27';if(U.terrain.water.some(w=>Math.hypot(x-w.x,y-w.y)<w.r))fill='#274f59';if(U.terrain.mines.some(m=>Math.hypot(x-m.x,y-m.y)<m.r))fill='#4a4742';diamond(x,y,fill)}
    for(const city of U.cities){const p=U.worldToScreen(city.x,city.y);c.fillStyle=city.color;c.fillRect(p.x-16,p.y-35,32,35);c.fillStyle='#2d1e1b';c.beginPath();c.moveTo(p.x-21,p.y-35);c.lineTo(p.x,p.y-55);c.lineTo(p.x+21,p.y-35);c.fill()}
    for(const st of U.terrain.stations){const p=U.worldToScreen(st.x,st.y);c.fillStyle='#a87e45';c.fillRect(p.x-10,p.y-12,20,12);c.fillStyle='#eee';c.font='10px Arial';c.fillText(st.type==='forge'?'Yunque':'Mesa',p.x-15,p.y-18)}
    const objects=[...U.npcs,...U.enemies.filter(e=>!e.dead),U.player].sort((a,b)=>(a.x+a.y)-(b.x+b.y));for(const o of objects){if(o===U.player)humanoid(o,true);else if(U.CharacterRenderer&&U.CharacterAdapter){const p=U.worldToScreen(o.x,o.y,4),visual=U.CharacterAdapter.getState(o);U.ctx.save();U.ctx.translate(p.x,p.y);U.CharacterRenderer.draw(U.ctx,visual,visual.scale?0.28*visual.scale:0.28);U.ctx.restore();label(o,p);if(o.hp!==undefined)hpBar(o,p)}else if(o.type==='wolf')wolf(o);else if(o.type==='troll'||o.type==='boss')troll(o);else humanoid(o,false)}
    if(U.player.target&&!U.player.target.dead){const p=U.worldToScreen(U.player.target.x,U.player.target.y);c.strokeStyle='#ff655d';c.lineWidth=3;c.beginPath();c.ellipse(p.x,p.y+9,25,11,0,0,Math.PI*2);c.stroke();c.fillStyle='#ff655d';c.beginPath();c.moveTo(p.x,p.y-76);c.lineTo(p.x-8,p.y-88);c.lineTo(p.x+8,p.y-88);c.closePath();c.fill()}
    for(const corpse of U.state.corpses){const p=U.worldToScreen(corpse.x,corpse.y);c.fillStyle='#7d2727';c.fillRect(p.x-14,p.y-3,28,11);c.fillStyle='#ddd';c.font='11px Arial';c.fillText('Cadáver',p.x-22,p.y-10)}for(const pr of U.state.projectiles){const p=U.worldToScreen(pr.x,pr.y);c.fillStyle=pr.spell?'#ff9b37':'#ddd';c.beginPath();c.arc(p.x,p.y-18,5,0,Math.PI*2);c.fill()}for(const ef of U.state.effects){const p=U.worldToScreen(ef.x,ef.y);if(ef.type==='float'){c.fillStyle=ef.color;c.font='bold 14px Arial';c.fillText(ef.text,p.x,p.y-40-ef.life*18)}else if(ef.type==='portal'){c.strokeStyle='#7f58d9';c.lineWidth=5;c.beginPath();c.ellipse(p.x,p.y-18,15,27,0,0,Math.PI*2);c.stroke()}else{c.fillStyle='#fff';c.fillText(ef.text||'✦',p.x,p.y-35)}}
  };
})(window.Ultra=window.Ultra||{});
