(function(U){
  const danger=['#fff0a3','#ffe13b','#f5a15a','#d96a2d','#a9202c','#691e2b','#6b3d88','#6e4d33','#171717','#fffbe8'];
  const defs={
    wolf:{name:'Lobo gris',hp:55,dmg:6,speed:2.8,color:'#776c5d',danger:0,loot:[['gold',1],['bandage',.25],['leatherChest',.04],['herb',.35]]},
    zombie:{name:'Muerto errante',hp:85,dmg:9,speed:1.8,color:'#65725c',danger:2,loot:[['gold',1],['herb',.35],['manaPotion',.1],['ringLife',.025]]},
    bandit:{name:'Bandido gris',hp:100,dmg:11,speed:2.2,color:'#7b5149',danger:3,loot:[['gold',1],['bandage',.55],['ironSword',.08],['helmet',.07],['potion',.15]]},
    troll:{name:'Troll de piedra',hp:180,dmg:16,speed:1.5,color:'#5e7851',danger:5,loot:[['trollHide',1],['gold',1],['greatSword',.055],['shield',.075],['contract110',.015]]},
    boss:{name:'Guardián del Umbral',hp:650,dmg:24,speed:1.2,color:'#5e356f',danger:8,loot:[['contract110',.45],['contract115',.18],['contract120',.05],['ringLife',.25],['gold',1],['greatSword',.2]]}
  };
  U.spawnEnemy=function(type,x,y,boss=false,variant=null){const base=defs[boss?'boss':type];let d={...base};variant=variant||((!boss&&Math.random()<.09)?'exalted':(!boss&&Math.random()<.025?'renowned':null));if(variant==='exalted')d={...d,name:'Exaltado '+d.name,hp:Math.round(d.hp*3),dmg:Math.round(d.dmg*1.8),speed:d.speed*1.55,color:'#d8ad32',danger:Math.min(9,d.danger+3)};if(variant==='renowned')d={...d,name:'Notable '+d.name,hp:Math.round(d.hp*5),dmg:Math.round(d.dmg*2.35),speed:d.speed*1.15,color:'#743b86',danger:Math.min(9,d.danger+5)};U.enemies.push({...d,type,boss,variant,nameColor:danger[d.danger],x,y,maxHp:d.hp,attackCd:0,dead:false,radius:boss?.7:.42,status:'hostile'})};
  U.toggleBattle=function(){U.state.battle=!U.state.battle;U.sound('ui');if(!U.state.battle){U.state.autoAttack=false;U.player.target=null}U.ui.updateBattleUI()};
  U.toggleAutoAttack=function(){if(!U.state.battle)return U.toast('Entra en modo Batalla.');if(!U.player.target||U.player.target.dead)return U.toast('Marca un enemigo primero.');U.state.autoAttack=!U.state.autoAttack;U.ui.updateBattleUI()};
  U.attack=function(){if(!U.state.battle||!U.player.target||U.player.target.dead)return false;const t=U.player.target,weapon=U.player.equipment.weapon?U.itemDefs[U.player.equipment.weapon.id]:U.itemDefs.gauntlets,range=weapon.ranged?9:(weapon.skill==='Esgrima'?1.85:1.45);if(U.dist(U.player,t)>range||U.player.attackCd>0)return false;U.player.attackCd=weapon.ranged?1.05:(weapon.twoHand?1.05:.68);U.player.attackAnim=.42;U.player.attackType=weapon.skill||'Pelea';U.sound(weapon.ranged?'ui':'sword');let dmg=weapon.damage+(U.player.skills[weapon.skill]||20)*.07+U.player.skills.Tácticas*.04+U.rnd(-2,3);if(weapon.ranged){if(U.countItem('arrow')<1){U.state.autoAttack=false;U.toast('No tienes flechas.');return false}U.removeItem('arrow',1);U.state.projectiles.push({x:U.player.x,y:U.player.y,target:t,speed:12,damage:dmg,physical:true})}else U.hitEnemy(t,dmg);U.raiseSkill(weapon.skill,.11);U.raiseSkill('Tácticas',.07);return true};
  U.hitEnemy=function(t,dmg){dmg=Math.max(1,Math.round(dmg));t.hp-=dmg;t.hitAnim=.18;U.sound('hit');U.state.effects.push({type:'float',x:t.x,y:t.y,text:'-'+dmg,color:'#ffd4c8',life:1});if(t.hp<=0)U.killEnemy(t)};
  U.killEnemy=function(t){t.dead=true;t.hp=0;t.deathAnim=.8;U.sound('death');const items=[];for(const [id,ch] of t.loot)if(Math.random()<=ch)items.push({id,qty:id==='gold'?Math.round(U.rnd(t.variant?45:18,t.boss?260:t.variant?150:65)):1,insured:false,uid:Math.random().toString(36).slice(2)});if(t.variant==='exalted'){items.push({id:U.pick(['potion','manaPotion','ironIngot','copperIngot']),qty:Math.round(U.rnd(2,6)),insured:false});if(Math.random()<.35)items.push({id:U.pick(['helmet','boots','cloak','shield']),qty:1,insured:false})}if(t.variant==='renowned'){items.push({id:U.pick(['greatSword','ringLife','contract110']),qty:1,insured:false});items.push({id:'gold',qty:Math.round(U.rnd(100,260)),insured:false})}U.state.corpses.push({name:'Cadáver de '+t.name,x:t.x,y:t.y,items,life:300,owner:'player'});U.player.target=null;U.state.autoAttack=false;U.toast(t.name+' ha muerto.');U.ui.updateBattleUI();setTimeout(()=>{t.dead=false;t.hp=t.maxHp;t.x+=U.rnd(-3,3);t.y+=U.rnd(-3,3)},120000)};
  U.healBandage=function(){if(U.player.healCd>0||U.player.bandaging)return U.toast('No puedes vendarte todavía.');if(U.countItem('bandage')<1)return U.toast('No tienes vendas.');U.removeItem('bandage',1);U.player.bandaging={t:2.2,total:2.2};U.toast('Comienzas a vendarte…');U.sound('heal');U.raiseSkill('Curar',.08)};
  U.usePotion=function(){if(U.countItem('potion')<1)return U.toast('No tienes pociones.');U.removeItem('potion',1);U.player.hp=Math.min(U.player.maxHp,U.player.hp+45);U.toast('Bebes una poción.');U.ui.refreshHUD()};
})(window.Ultra=window.Ultra||{});